apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: helmapis.operator.ibm.com
spec:
  group: operator.ibm.com
  names:
    kind: HelmAPI
    listKind: HelmAPIList
    plural: helmapis
    singular: helmapi
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: HelmAPI is the Schema for the helmapis API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        spec:
          properties:
            auditService:
              type: object
              properties:
                config:
                  type: object
                  properties:
                    enabled:
                      type: boolean
                image:
                  type: object
                  properties:
                    pullPolicy:
                      type: string
                    repository:
                      type: string
                    tag:
                      type: string
                name:
                  type: string
              x-kubernetes-preserve-unknown-fields: true
            helmapi:
              type: object
              properties:
                env:
                  type: object
                  properties:
                    CLUSTER_CA_DOMAIN:
                      type: string
                    CLUSTER_PORT:
                      type: integer
                    DBHOST:
                      type: string
                    DBPORT:
                      type: string
                    HTTP_PROXY:
                      type: string
                    HTTPS_PROXY:
                      type: string
                    ISICP:
                      type: boolean
                    LOAD_ROUTES:
                      type: string
                    MONGO_ISSSL:
                      type: boolean
                    MONGO_SSL_CA:
                      type: string
                    MONGO_SSL_CERT: 
                      type: string
                    MONGO_SSL_KEY: 
                      type: string
                    NO_PROXY: 
                      type: string
                    PROXY_EXTERNAL_ADDR: 
                      type: string
                    PROXY_ROUTE: 
                      type: string
                    SET_TLS: 
                      type: string
                    WLP_REDIRECT_URL:
                      type: string
                image:
                  type: object
                  properties:
                    name:
                      type: string
                    pullPolicy:
                      type: string
                    repository:
                      type: string
                    tag:
                      type: string
                resources:
                  type: object
                  properties:
                    limits:
                      type: object
                      properties:
                        cpu:
                          type: string
                        memory: 
                          type: string
                    requests:
                      type: object
                      properties:
                        cpu:
                          type: string
                        memory: 
                          type: string
                secretKeyRef:
                  type: object
                  properties:
                    clientIdSecretKey:
                      type: string
                    clientIdSecretName:
                      type: string
                    clientSecretSecretKey:
                      type: string
                    clientSecretSecretName:
                      type: string
                    dbSecretName:
                      type: string
                    dbSecretPassKey:
                      type: string
                    dbSecretUserKey:
                      type: string
                service:
                  type: object
                  properties:
                    name:
                      type: string
                    port:
                      type: integer #maybe string?
                    portName:
                      type: string
                sharedassets:
                  type: object
                  properties:
                    name:
                      type: string
                    path:
                      type: string
                volumemounts:
                  type: object
                  properties:
                    helmApiCertsMountPath: 
                      type: string
                    helmApiCertsName: 
                      type: string
                    mongoCaMountPath: 
                      type: string
                    mongoCaName: 
                      type: string
                    mongoClientCertMountPath: 
                      type: string
                    mongoClientCertName: 
                      type: string
            nodeSelector:
              type: object
            replicaCount:
              type: integer
            rudder:
              type: object
              properties:
                env:
                  type: object
                  properties:
                    RUDDER_CLIENT_CERTS:
                      type: string
                    RUDDER_TILLER_ADDRESS:
                      type: string
                    USE_TLS:
                      type: string
                image:
                  type: object
                  properties:
                    name:
                      type: string
                    pullPolicy:
                      type: string
                    repository:
                      type: string
                    tag:
                      type: string
                ports:
                  type: object
                  properties:
                    containerPort:
                      type: integer #maybe string?
                    containerPortName:
                      type: string
                    protocol:
                      type: string
                resources:
                  type: object
                  properties:
                    limits:
                      type: object
                      properties:
                        cpu:
                          type: string
                        memory: 
                          type: string
                    requests:
                      type: object
                      properties:
                        cpu:
                          type: string
                        memory: 
                          type: string
                volumeMounts:
                  type: object
                  properties:
                    rudderCacheMountPath:
                      type: string
                    rudderCacheName:
                      type: string
                    rudderCertsMountPath:
                      type: string
                    rudderCertsName:
                      type: string
            runAsUser:
              type: integer
            tiller:
              type: object
              properties:
                defaultAdminUser:
                  type: string
                image:
                  type: object
                  properties:
                    name:
                      type: string
                    pullPolicy:
                      type: string
                    repository:
                      type: string
                    tag:
                      type: string
                nodePort:
                  type: integer #maybe string?
                resources:
                  type: object
                  properties:
                    limits:
                      type: object
                      properties:
                        cpu:
                          type: string
                        memory: 
                          type: string
                    requests:
                      type: object
                      properties:
                        cpu:
                          type: string
                        memory: 
                          type: string
            volumes:
              type: object
              properties:
                helmApiCertsName: 
                  type: string
                helmApiCertsSecretName: 
                  type: string
                mongoCaCertName: 
                  type: string
                mongoCaCertSecretName: 
                  type: string
                mongoClientCertName:
                  type: string
                mongoClientCertSecretName: 
                  type: string
                rudderCertsName: 
                  type: string
                rudderCertsSecretName: 
                  type: string                           
          required:
          - helmapi
          - rudder
          - runAsUser
          - tiller
          type: object
        status:
          properties:
            conditions:
              items:
                properties:
                  lastTransitionTime:
                    type: string
                  lastUpdateTime:
                    type: string
                  message:
                    type: string
                  reason:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
                required:
                - status
                - type
                type: object
              type: array
            deployedRelease:
              properties:
                manifest:
                  type: string
                name:
                  type: string
              type: object
          type: object
      required:
      - metadata
      - spec
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
