---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: "helm-api"
  labels:
    app: helm-api
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    app.kubernetes.io/name: "helm-api"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  secretName: "{{ .Values.volumes.helmApiCertsSecretName }}"
  issuerRef:
    name: cs-ca-clusterissuer
    kind: ClusterIssuer
  commonName: "helm-api"
  dnsNames:
  - helm-api
  - helm-api.{{ .Release.Namespace }}
  - helm-api.{{ .Release.Namespace }}.svc
  - localhost
  - 127.0.0.1
