---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: helm-api-swagger
  annotations:
    kubernetes.io/ingress.class: "ibm-icp-management"
    icp.management.ibm.com/rewrite-target: "/api/swagger/swagger.json"
  labels:
    app: "helm-api"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    app.kubernetes.io/name: "helm-api"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  rules:
  - http:
      paths:
      - path: /helm-api/api/swagger/swagger.json
        backend:
          serviceName: "{{ .Values.helmapi.service.name }}"
          servicePort: {{ .Values.helmapi.service.port }}
