---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: "rudder"
  labels:
    app: helm-api
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    app.kubernetes.io/name: "helm-api"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  secretName: "{{ .Values.volumes.rudderCertsSecretName }}"
  issuerRef:
    name: cs-ca-clusterissuer
    kind: ClusterIssuer
  commonName: "rudder"
  dnsNames:
  - localhost:5000
  - 127.0.0.1:5000

---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.volumes.rudderCertsSecretName }}"
  namespace: {{ .Release.Namespace }}
  labels:
    app: "helm-api"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    app.kubernetes.io/name: "helm-api"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
