---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: "helm-api"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    app.kubernetes.io/name: "helm-api"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  name: tiller-deploy
  namespace: {{ .Release.Namespace }}
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: grpc
    nodePort: {{ .Values.tiller.nodePort }}
    port: 44134
    protocol: TCP
    targetPort: 44134
  selector:
    app: helm
    name: tiller
  sessionAffinity: None
  type: NodePort

---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: "helm-api"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    app.kubernetes.io/name: "helm-api"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  name: tiller-deploy
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helm
      name: tiller
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        seccomp.security.alpha.kubernetes.io/pod: docker/default
        productName: IBM Cloud Platform Common Services
        productID: "068a62892a1e4db39641342e592daa25"
        productVersion: "3.3.0"
        productMetric: FREE
        clusterhealth.ibm.com/dependencies: "auth-idp, icp-management-ingress"
      labels:
        app: helm
        name: tiller
        app.kubernetes.io/instance: "{{ .Release.Name }}"
        app.kubernetes.io/managed-by: "{{ .Release.Service }}"
        app.kubernetes.io/name: tiller
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      hostNetwork: false
      hostPID: false
      hostIPC: false
      containers:
      - env:
        - name: IAM_HOST
          value: "platform-identity-management"
        - name: IAM_PORT
          value: "4500"
        - name: TILLER_HISTORY_MAX
          value: "5"
        - name: TILLER_NAMESPACE
          value: {{ .Release.Namespace }}
        - name: TILLER_TLS_CERTS
          value: /etc/certs
        - name: TILLER_TLS_VERIFY
          value: "1"
        - name: TILLER_TLS_ENABLE
          value: "1"
        - name: CIPHERSUITES
          value: "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_256_GCM_SHA384"
        - name: default_admin_user
          value: "{{ .Values.tiller.defaultAdminUser }}"
        - name: CLUSTER_PORT
          value: "443"
        image: "{{ .Values.tiller.image.repository }}:{{ .Values.tiller.image.tag }}"
        imagePullPolicy: {{ .Values.tiller.image.pullPolicy }}
        livenessProbe:
          httpGet:
            path: "/liveness"
            port: 44135
            scheme: HTTP
          initialDelaySeconds: 1
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        name: {{ .Values.tiller.image.name }}
        securityContext:
          runAsNonRoot: true
          runAsUser: {{ .Values.runAsUser }}
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          privileged: false
          capabilities:
            drop:
            - ALL
        readinessProbe:
          httpGet:
            path: "/readiness"
            port: 44135
            scheme: HTTP
          initialDelaySeconds: 1
          timeoutSeconds: 1
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        resources:
          {{ toYaml .Values.tiller.resources | nindent 10 }}
        volumeMounts:
        - mountPath: /etc/certs
          name: tiller-certs
      dnsPolicy: ClusterFirstWithHostNet
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: tiller-sa
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Exists
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
        operator: Exists
      volumes:
      - name: tiller-certs
        secret:
          defaultMode: 420
          secretName: tiller-secret
