---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: tiller-deploy
  labels:
    release: "{{ .Release.Name }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    app.kubernetes.io/name: "tiller-deploy"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  secretName: "tiller-secret"
  issuerRef:
    name: cs-ca-clusterissuer
    kind: ClusterIssuer
  commonName: "tiller-deploy"
  dnsNames:
  - tiller-deploy:44134
  - tiller-deploy.{{ .Release.Namespace }}:44134
  - tiller-deploy.{{ .Release.Namespace }}.svc:44134