---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: tiller-deploy
  labels:
    app: "helm-api"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    app.kubernetes.io/name: "helm-api"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  secretName: "tiller-secret"
  issuerRef:
    name: cs-ca-clusterissuer
    kind: ClusterIssuer
  commonName: "tiller-deploy"
  dnsNames:
  - tiller-deploy:44134
  - tiller-deploy.{{ .Release.Namespace }}:44134
  - tiller-deploy.{{ .Release.Namespace }}.svc:44134

---
apiVersion: v1
kind: Secret
metadata:
  name:  tiller-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: "delete"
    ibm.com/iam-service.api-key: tiller-api-key
    ibm.com/iam-service.id: tiller-service-id
    ibm.com/iam-service.name: tiller-service
  labels:
    app: "helm-api"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    app.kubernetes.io/name: "helm-api"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"